### ISSUE TITLE
Throw errors when job.complete is given invalid data

### ISSUE THREAD

**Issue by TylerHAtkinson** [camunda/camunda-8-js-sdk#247]
## SDK Component
Zeebe

## Expected Behavior
When passing an array of data to `job.complete`, I would expect an error to be thrown since zeebe doesn't seem to be able to properly deal with arrays.

## Current Behavior
Possibly related to: https://github.com/camunda/camunda-8-js-sdk/issues/236
Currently passing an array of data to job.complete (`job.complete([{ var1: 1 }])`) does not throw an error, and the token is stuck on that task

## Possible Solution
In `parseVariablesAndCustomHeadersToJSON`, add
```typescript
if(Array.isArray(response.variables)) {
  throw new Error('Unable to parse Array into variables'); //Or something like that
}
```
Also if there's any other values that would cause this behavior, it would be nice to have those explicitly thrown

## Steps to Reproduce
When handling a `ZeebeJob`, pass an array of data into `job.complete`
  - `job.complete([{ var1: 1 }] as any)`

Notice that the token is stuck with no incidents reported, and no errors thrown

## Context (Environment)
I know the typing for `complete` technically doesn't allow arrays, due to a type assertion we ended up accidentally passing an array. While this was easy to fix, it was difficult to diagnose the issue since from adding `console.logs` it seemed like everything ran successfully

**Comment by jwulf** [comment]
Thanks for reporting this. 

Hmmmm... this is a very strange behaviour, and I don't know that a run-time type guard here is the best place to address this in the system. 

I would expect that _if no error is thrown by the gRPC API call to Zeebe_ that the CompleteJob operation _completed successfully_. 

I tested this scenario, and I see what you report: the gRPC API throws no error, the process does not throw an incident and the job is not completed. The job is sent for a retry, but because it doesn't fail on the client, no retry decrement occurs (retry decrement is the responsibility of the client making the FailJob RPC call).

Thus, the job goes into an infinite retry loop.

I will check with the Zeebe engineering team. I have a vague memory of this coming up a few years ago. Let me look into it.

**Comment by jwulf** [comment]
We'll guard against it in the client immediately - I don't know at what point they'll be able to re-engineer the API. 

The new REST API endpoint for completing a job (in 8.6) throws a 400 if you try to post an array to it.

**Comment by jwulf** [comment]
`stringifyVariables` is the function that needs the guard. That one JSON stringifies the variables for a request to the gateway, and is called from the ZBClient `completeJob` method - which is how the worker completes jobs.

The `parseVariablesAndCustomHeadersToJSON` function is used for parsing responses from the gateway from stringified JSON to JS objects.
