### ISSUE TITLE
Add "Fully Supported" and definition to README

### ISSUE THREAD

**Issue by jwulf** [camunda/camunda-8-js-sdk#70]
## What does "supported" mean?

This is the official supported-by-Camunda Nodejs SDK for Camunda Platform 8.

The  Node.js SDK will not always support all features of Camunda Platform 8 immediately upon their release. Complete API coverage for a platform release will lag behind the platform release. 

Prioritisation of implementing features is influenced by customer demand.

**Comment by MaxTru** [comment]
Thanks for initiating this.

Some notes:
* Let's please not use the term `fully supported` because there is no such thing as `fully / partly / 20% supported`.
  * Essentially => we support Camunda 8 as specified, where the specification is what we put into the docs. 
  * Following, it would be sufficient to put the node-js SDK into docs.camunda.io and state "The SDK supports the following features / APIS / ...``
  
> You can get an Enterprise Support agreement with Camunda and get technical support for using this SDK in development and production. With a support agreement, you can open tickets and get technical support on using the features that the SDK implements.
* That is true, but I don't see the need to add a specific note about this in the docs (again, we support what is specified).

> At the moment, we do not guarantee that the SDK will support all features of Camunda Platform 8 immediately upon their release.
>
> Our goal with the SDK to support the features of a minor release within the minor release window. This means, for example, that all 8.5 features are enabled by this SDK before the 8.6 release.

That makes sense, and I think is worth highlighting.

Thanks!
